Misc fix on log beeing flooded due to scope being dead
Error was:
[23:04:23][E][jomini_script_system.cpp:284]: Script system error!
  Error: remove_character_flag effect [ scope is dead during effect execution ]
  Script location: file: events/activities/chariot_race_activity/chariot_race_ongoing_events.txt line: 3914 (chariot_race.4031:after)
    file: events/activities/chariot_race_activity/chariot_race_ongoing_events.txt line: 3571 (chariot_race.4030:option)